### ISSUE TITLE
Disable/Enable voice assistance in settings

### ISSUE THREAD

**Issue by HatimLagzar** [roldanjr/productivity-timer#108]
**Is your feature request related to a problem? Please describe.**
I don't like the voice assistance.

**Describe the solution you'd like**
I would like to be able to disable/enable the voice assistance from the settings tab.

**Additional context**
When a work/break session close to end I hear a voice.

Thanks for this great app.

**Comment by roldanjrCodeArts9711** [comment]
This issue is being mention here #99 .

Just turn the sound button off @HatimLagzar .

![image](https://user-images.githubusercontent.com/38913069/88499678-299a3600-cff9-11ea-9448-a388edff1ad2.png)

I will try to add option disabling text-to-speech feature in the settings tab on my next release.

**Comment by HatimLagzar** [comment]
@roldanjrCodeArts9711 Thank you so much :)

**Comment by roldanjr** [comment]
I think I need to close this issue @HatimLagzar .
I just released [v3.1.0](https://github.com/roldanjr/productivity-timer/releases/tag/v3.1.0) with the feature you've requested.

Thanks for using the app. 😃

**Comment by HatimLagzar** [comment]
I installed the update thank you so much

**Comment by roldanjr** [comment]
No problem. Thanks for appreciating the app.
